JAVA_HOME="${TOMCAT_JAVA_HOME}"; export JAVA_HOME
CATALINA_HOME="${TOMCAT_ROOT}"; export CATALINA_HOME
JAVA_OPTS="${TOMCAT_JAVA_OPTS}"; export JAVA_OPTS
CATALINA_OPTS="${TOMCAT_CATALINA_OPTS}"; export CATALINA_OPTS
CATALINA_PID="${CATALINA_HOME}/logs/pid"; export CATALINA_PID
